# coding: utf-8

"""
    finAPI RESTful Services

    finAPI RESTful Services  # noqa: E501

    OpenAPI spec version: v1.41.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.client_configuration_api import ClientConfigurationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClientConfigurationApi(unittest.TestCase):
    """ClientConfigurationApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.client_configuration_api.ClientConfigurationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_edit_client_configuration(self):
        """Test case for edit_client_configuration

        Edit client configuration  # noqa: E501
        """
        pass

    def test_get_client_configuration(self):
        """Test case for get_client_configuration

        Get client configuration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
