# coding: utf-8

"""
    finAPI RESTful Services

    finAPI RESTful Services  # noqa: E501

    OpenAPI spec version: v1.41.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.update_multiple_transactions_params import UpdateMultipleTransactionsParams  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateMultipleTransactionsParams(unittest.TestCase):
    """UpdateMultipleTransactionsParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateMultipleTransactionsParams(self):
        """Test UpdateMultipleTransactionsParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_multiple_transactions_params.UpdateMultipleTransactionsParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
