# coding: utf-8

"""
    finAPI RESTful Services

    finAPI RESTful Services  # noqa: E501

    OpenAPI spec version: v1.41.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.direct_debit_ordering_response import DirectDebitOrderingResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestDirectDebitOrderingResponse(unittest.TestCase):
    """DirectDebitOrderingResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDirectDebitOrderingResponse(self):
        """Test DirectDebitOrderingResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.direct_debit_ordering_response.DirectDebitOrderingResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
