# coding: utf-8

"""
    finAPI RESTful Services

    finAPI RESTful Services  # noqa: E501

    OpenAPI spec version: v1.41.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.split_transactions_params import SplitTransactionsParams  # noqa: E501
from swagger_client.rest import ApiException


class TestSplitTransactionsParams(unittest.TestCase):
    """SplitTransactionsParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSplitTransactionsParams(self):
        """Test SplitTransactionsParams"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.split_transactions_params.SplitTransactionsParams()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
