# coding: utf-8

"""
    finAPI RESTful Services

    finAPI RESTful Services  # noqa: E501

    OpenAPI spec version: v1.41.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.categories_api import CategoriesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCategoriesApi(unittest.TestCase):
    """CategoriesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.categories_api.CategoriesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_category(self):
        """Test case for create_category

        Create a new category  # noqa: E501
        """
        pass

    def test_delete_all_categories(self):
        """Test case for delete_all_categories

        Delete all categories  # noqa: E501
        """
        pass

    def test_delete_category(self):
        """Test case for delete_category

        Delete a category  # noqa: E501
        """
        pass

    def test_get_and_search_all_categories(self):
        """Test case for get_and_search_all_categories

        Get and search all categories  # noqa: E501
        """
        pass

    def test_get_cash_flows(self):
        """Test case for get_cash_flows

        Get cash flows  # noqa: E501
        """
        pass

    def test_get_category(self):
        """Test case for get_category

        Get a category  # noqa: E501
        """
        pass

    def test_get_multiple_categories(self):
        """Test case for get_multiple_categories

        Get multiple categories  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
