# coding: utf-8

"""
    finAPI RESTful Services

    finAPI RESTful Services  # noqa: E501

    OpenAPI spec version: v1.42.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.transaction_data_with_identifier import TransactionDataWithIdentifier  # noqa: E501
from swagger_client.rest import ApiException


class TestTransactionDataWithIdentifier(unittest.TestCase):
    """TransactionDataWithIdentifier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionDataWithIdentifier(self):
        """Test TransactionDataWithIdentifier"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.transaction_data_with_identifier.TransactionDataWithIdentifier()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
