# coding: utf-8

"""
    finAPI RESTful Services

    finAPI RESTful Services  # noqa: E501

    OpenAPI spec version: v1.41.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.error_details import ErrorDetails  # noqa: E501
from swagger_client.rest import ApiException


class TestErrorDetails(unittest.TestCase):
    """ErrorDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testErrorDetails(self):
        """Test ErrorDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.error_details.ErrorDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
