# coding: utf-8

"""
    finAPI RESTful Services

    finAPI RESTful Services  # noqa: E501

    OpenAPI spec version: v1.41.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.mocks_and_tests_api import MocksAndTestsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMocksAndTestsApi(unittest.TestCase):
    """MocksAndTestsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.mocks_and_tests_api.MocksAndTestsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_mock_batch_update(self):
        """Test case for mock_batch_update

        Mock batch update  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
