# coding: utf-8

"""
    finAPI RESTful Services

    finAPI RESTful Services  # noqa: E501

    OpenAPI spec version: v1.41.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.mock_account_data import MockAccountData  # noqa: E501
from swagger_client.rest import ApiException


class TestMockAccountData(unittest.TestCase):
    """MockAccountData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMockAccountData(self):
        """Test MockAccountData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.mock_account_data.MockAccountData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
