# coding: utf-8

"""
    finAPI RESTful Services

    finAPI RESTful Services  # noqa: E501

    OpenAPI spec version: v1.42.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.transactions_data import TransactionsData  # noqa: E501
from swagger_client.rest import ApiException


class TestTransactionsData(unittest.TestCase):
    """TransactionsData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionsData(self):
        """Test TransactionsData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.transactions_data.TransactionsData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
