# coding: utf-8

"""
    finAPI RESTful Services

    finAPI RESTful Services  # noqa: E501

    OpenAPI spec version: v1.41.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.notification_rules_api import NotificationRulesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNotificationRulesApi(unittest.TestCase):
    """NotificationRulesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.notification_rules_api.NotificationRulesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_notification_rule(self):
        """Test case for create_notification_rule

        Create a new notification rule  # noqa: E501
        """
        pass

    def test_delete_all_notification_rules(self):
        """Test case for delete_all_notification_rules

        Delete all notification rules  # noqa: E501
        """
        pass

    def test_delete_notification_rule(self):
        """Test case for delete_notification_rule

        Delete a notification rule  # noqa: E501
        """
        pass

    def test_get_and_search_all_notification_rules(self):
        """Test case for get_and_search_all_notification_rules

        Get and search all notification rules  # noqa: E501
        """
        pass

    def test_get_notification_rule(self):
        """Test case for get_notification_rule

        Get a notification rule  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
