# coding: utf-8

"""
    finAPI RESTful Services

    finAPI RESTful Services  # noqa: E501

    OpenAPI spec version: v1.41.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.cash_flow_list import CashFlowList  # noqa: E501
from swagger_client.rest import ApiException


class TestCashFlowList(unittest.TestCase):
    """CashFlowList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCashFlowList(self):
        """Test CashFlowList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.cash_flow_list.CashFlowList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
