# coding: utf-8

"""
    finAPI RESTful Services

    finAPI RESTful Services  # noqa: E501

    OpenAPI spec version: v1.41.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.paging import Paging  # noqa: F401,E501
from swagger_client.models.user_info import UserInfo  # noqa: F401,E501


class PageableUserInfoList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'users': 'list[UserInfo]',
        'paging': 'Paging'
    }

    attribute_map = {
        'users': 'users',
        'paging': 'paging'
    }

    def __init__(self, users=None, paging=None):  # noqa: E501
        """PageableUserInfoList - a model defined in Swagger"""  # noqa: E501

        self._users = None
        self._paging = None
        self.discriminator = None

        self.users = users
        self.paging = paging

    @property
    def users(self):
        """Gets the users of this PageableUserInfoList.  # noqa: E501

        List of users information  # noqa: E501

        :return: The users of this PageableUserInfoList.  # noqa: E501
        :rtype: list[UserInfo]
        """
        return self._users

    @users.setter
    def users(self, users):
        """Sets the users of this PageableUserInfoList.

        List of users information  # noqa: E501

        :param users: The users of this PageableUserInfoList.  # noqa: E501
        :type: list[UserInfo]
        """
        if users is None:
            raise ValueError("Invalid value for `users`, must not be `None`")  # noqa: E501

        self._users = users

    @property
    def paging(self):
        """Gets the paging of this PageableUserInfoList.  # noqa: E501

        Information for pagination  # noqa: E501

        :return: The paging of this PageableUserInfoList.  # noqa: E501
        :rtype: Paging
        """
        return self._paging

    @paging.setter
    def paging(self, paging):
        """Sets the paging of this PageableUserInfoList.

        Information for pagination  # noqa: E501

        :param paging: The paging of this PageableUserInfoList.  # noqa: E501
        :type: Paging
        """
        if paging is None:
            raise ValueError("Invalid value for `paging`, must not be `None`")  # noqa: E501

        self._paging = paging

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PageableUserInfoList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
