# coding: utf-8

"""
    finAPI RESTful Services

    finAPI RESTful Services  # noqa: E501

    OpenAPI spec version: v1.42.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class UserIdentifiersList(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'deleted_users': 'list[str]',
        'non_deleted_users': 'list[str]'
    }

    attribute_map = {
        'deleted_users': 'deletedUsers',
        'non_deleted_users': 'nonDeletedUsers'
    }

    def __init__(self, deleted_users=None, non_deleted_users=None):  # noqa: E501
        """UserIdentifiersList - a model defined in Swagger"""  # noqa: E501

        self._deleted_users = None
        self._non_deleted_users = None
        self.discriminator = None

        self.deleted_users = deleted_users
        self.non_deleted_users = non_deleted_users

    @property
    def deleted_users(self):
        """Gets the deleted_users of this UserIdentifiersList.  # noqa: E501

        List of identifiers of deleted users (in ascending order)  # noqa: E501

        :return: The deleted_users of this UserIdentifiersList.  # noqa: E501
        :rtype: list[str]
        """
        return self._deleted_users

    @deleted_users.setter
    def deleted_users(self, deleted_users):
        """Sets the deleted_users of this UserIdentifiersList.

        List of identifiers of deleted users (in ascending order)  # noqa: E501

        :param deleted_users: The deleted_users of this UserIdentifiersList.  # noqa: E501
        :type: list[str]
        """
        if deleted_users is None:
            raise ValueError("Invalid value for `deleted_users`, must not be `None`")  # noqa: E501

        self._deleted_users = deleted_users

    @property
    def non_deleted_users(self):
        """Gets the non_deleted_users of this UserIdentifiersList.  # noqa: E501

        List of identifiers of not deleted users (in ascending order)  # noqa: E501

        :return: The non_deleted_users of this UserIdentifiersList.  # noqa: E501
        :rtype: list[str]
        """
        return self._non_deleted_users

    @non_deleted_users.setter
    def non_deleted_users(self, non_deleted_users):
        """Sets the non_deleted_users of this UserIdentifiersList.

        List of identifiers of not deleted users (in ascending order)  # noqa: E501

        :param non_deleted_users: The non_deleted_users of this UserIdentifiersList.  # noqa: E501
        :type: list[str]
        """
        if non_deleted_users is None:
            raise ValueError("Invalid value for `non_deleted_users`, must not be `None`")  # noqa: E501

        self._non_deleted_users = non_deleted_users

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserIdentifiersList):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
