# coding: utf-8

"""
    finAPI RESTful Services

    finAPI RESTful Services  # noqa: E501

    OpenAPI spec version: v1.42.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class VerificationStatusResource(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user_id': 'str',
        'is_user_verified': 'bool'
    }

    attribute_map = {
        'user_id': 'userId',
        'is_user_verified': 'isUserVerified'
    }

    def __init__(self, user_id=None, is_user_verified=False):  # noqa: E501
        """VerificationStatusResource - a model defined in Swagger"""  # noqa: E501

        self._user_id = None
        self._is_user_verified = None
        self.discriminator = None

        self.user_id = user_id
        self.is_user_verified = is_user_verified

    @property
    def user_id(self):
        """Gets the user_id of this VerificationStatusResource.  # noqa: E501

        User's identifier  # noqa: E501

        :return: The user_id of this VerificationStatusResource.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this VerificationStatusResource.

        User's identifier  # noqa: E501

        :param user_id: The user_id of this VerificationStatusResource.  # noqa: E501
        :type: str
        """
        if user_id is None:
            raise ValueError("Invalid value for `user_id`, must not be `None`")  # noqa: E501

        self._user_id = user_id

    @property
    def is_user_verified(self):
        """Gets the is_user_verified of this VerificationStatusResource.  # noqa: E501

        User's verification status  # noqa: E501

        :return: The is_user_verified of this VerificationStatusResource.  # noqa: E501
        :rtype: bool
        """
        return self._is_user_verified

    @is_user_verified.setter
    def is_user_verified(self, is_user_verified):
        """Sets the is_user_verified of this VerificationStatusResource.

        User's verification status  # noqa: E501

        :param is_user_verified: The is_user_verified of this VerificationStatusResource.  # noqa: E501
        :type: bool
        """
        if is_user_verified is None:
            raise ValueError("Invalid value for `is_user_verified`, must not be `None`")  # noqa: E501

        self._is_user_verified = is_user_verified

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, VerificationStatusResource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
